### ISSUE TITLE
Implement the new API method for getting messages from a timestamp(as JSON)

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/HermesBot#5]
When this is implemented in the web client & bot library, this new method should replace the old one

**Comment by ThePerkinrex** [comment]
The only thing left to update to the new method is this.
When that happens, this issue will be closed, and issue #2 will be on its way to being closed

**Comment by spaceface777** [comment]
The method was already implemented a while ago, now we only need to fix #2.
